#pragma once

#define TENSORFLOWCPY_VERSION "0.0.1"

#define TENSORFLOWCPY_VERSION_MAJOR 0
#define TENSORFLOWCPY_VERSION_MINOR 0
#define TENSORFLOWCPY_VERSION_PATCH 1
#define TENSORFLOWCPY_VERSION_TWEAK 0
